<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>p01_hello_ros2</name>
  <version>0.1.0</version>
  <description>ROS 2 Humble 学习示例 01：工作空间、包结构与第一个 C++ 节点（最小发布者/订阅者）</description>
  <maintainer email="li_xin_long@foxmail.com">Xinlong-Li</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
